name: 'Send cancelled message'
description: 'Send a message to the PR when the action is cancelled'

runs:
  using: "composite"
  steps:
    - uses: actions/github-script@v7
      with:
        script: |
          github.rest.issues.createComment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.issue.number,
            body: '⚠️ Command was cancelled ⚠️\n\nGitHub action run: [link](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})'
          })
