name: Integration Tests

on:
  workflow_dispatch:
  pull_request:
    types: [ labeled ]
  issue_comment:
    types:
      - created
jobs:
  integration_test:
    if: github.event_name == 'workflow_dispatch' || github.event.label.name == 'for_integration_tests' || (github.event_name == 'issue_comment' && startsWith(github.event.comment.body, '/run_integration_tests'))
    runs-on: [ ubuntu-latest ]
    steps:
      - uses: actions/checkout@v4
      - name: Call Dagger Function
        uses: dagger/dagger-for-github@8.0.0
        with:
          version: "latest"
          module: ./tests
          args: all --with-running-airflow-tasks
          cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}

      - name: Remove 'for_integration_tests' label if exists
        if: success() && github.event_name == 'pull_request'
        uses: actions-ecosystem/action-remove-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: for_integration_tests

      - name: Add 'integration_passed' label
        if: success()
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: integration_passed
