name: Integration Tests

on:
  workflow_dispatch:
  issue_comment:
    types:
      - created
jobs:
  integration_test:
    if: github.event_name == 'workflow_dispatch' || (github.event_name == 'issue_comment' && startsWith(github.event.comment.body, '/run_integration_tests'))
    runs-on: [ ubuntu-latest ]
    steps:
      - uses: actions/checkout@v4
      - name: Call Dagger Function
        uses: dagger/dagger-for-github@8.0.0
        with:
          version: "latest"
          module: ./tests
          args: all --with-running-airflow-tasks
          cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}
